language: node_js

node_js:
  - "6"

sudo: required

before_script:
  - npm install grunt-cli -g
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
  - grunt test
  
services:
  - mongodb